version: "3"

services:
  vote:
    image: georgerodriguex/vote:latest
    command: python app.py
    ports:
      - "1234:80"
    networks:
      - front-tier
      - back-tier
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  worker:
    image: georgerodriguex/worker:latest
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  result:
    image: georgerodriguex/result:latest
    command: nodemon server.js
    ports:
      - "1235:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    deploy: 
      placement:
        constraints:
          - "node.role==manager"

volumes:
        db-data:

networks:
        front-tier:
        back-tier:

