version: "3"

services:
  vote:
    image: georgerodriguex/vote:latest
    command: python app.py
    ports:
      - "1234:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: georgerodriguex/worker:latest
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  result:
    image: georgerodriguex/result:latest
    command: nodemon server.js
    ports:
      - "1235:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
        db-data:

networks:
        front-tier:
        back-tier:

