apiVersion: v1
kind: Namespace
metadata:
  name: examplevotting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votting-app
  namespace: examplevotting
  labels:
    app: votting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votting
  template:
    metadata:
      labels:
        app: votting
    spec:
      containers:
      - name: votting
        image: georgerodriguex/vote
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: votting-service
  namespace: examplevotting
spec:
  type: NodePort
  selector:
    app: votting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: examplevotting
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: examplevotting
spec:
  ports:
    - protocol: TCP
      port: 6379

