apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: default
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    vote: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000