apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      vote: web
  template:
    metadata:
      labels:
        vote: web
    spec:
      containers:
      - name: vote
        image: georgerodriguex/vote:latest
